##### Imports

In [2]:
import numpy as np 
import pandas as pd 

#### Creating Arrays for further manipulation 

In [15]:
array1 = np.ones((10, 10))
array2 = np.zeros((8, 8))

In [6]:
print(f"Array 1:\n {array1}")
print(f"Array 2:\n {array2}")

Array 1:
 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
Array 2:
 [[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### Combining the arrays 

In [16]:
array1[1:9, 1:9] = array2
array1

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### Testing the another matrix 

In [21]:
input_matrix = np.full((6, 6), 8)
array1[2:8, 2:8] = input_matrix
print(array1)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 8. 8. 8. 8. 8. 8. 0. 1.]
 [1. 0. 8. 8. 8. 8. 8. 8. 0. 1.]
 [1. 0. 8. 8. 8. 8. 8. 8. 0. 1.]
 [1. 0. 8. 8. 8. 8. 8. 8. 0. 1.]
 [1. 0. 8. 8. 8. 8. 8. 8. 0. 1.]
 [1. 0. 8. 8. 8. 8. 8. 8. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [24]:
input_matrix2 = np.full((4, 4), 5)
array1[3:7, 3:7] = input_matrix2
print(array1)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 8. 8. 8. 8. 8. 8. 0. 1.]
 [1. 0. 8. 5. 5. 5. 5. 8. 0. 1.]
 [1. 0. 8. 5. 5. 5. 5. 8. 0. 1.]
 [1. 0. 8. 5. 5. 5. 5. 8. 0. 1.]
 [1. 0. 8. 5. 5. 5. 5. 8. 0. 1.]
 [1. 0. 8. 8. 8. 8. 8. 8. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [26]:
input_matrix3 = np.full((2, 2), 2)
array1[4:6, 4:6] = input_matrix3
print(array1)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 8. 8. 8. 8. 8. 8. 0. 1.]
 [1. 0. 8. 5. 5. 5. 5. 8. 0. 1.]
 [1. 0. 8. 5. 2. 2. 5. 8. 0. 1.]
 [1. 0. 8. 5. 2. 2. 5. 8. 0. 1.]
 [1. 0. 8. 5. 5. 5. 5. 8. 0. 1.]
 [1. 0. 8. 8. 8. 8. 8. 8. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [27]:
print(f"Determinate of newly created matrix: {np.linalg.det(array1)}")

Determinate of newly created matrix: 0.0


### Test array for determinant

In [28]:
det_arr = np.array([[1,2,0],[2,1,0], [0,0,-3]])

print(np.linalg.det(det_arr))

8.999999999999998
